### PR TITLE
close #21 basic supervision strategy implementation

### LINKED ISSUE #21: Actor supervision strategy
This issue is created to track a discussion of actor supervision strategy. When an actor fails in runtime there is no strategy defined how to handle those. It leads to a "hung" process.

copy/paste from a pr discussion:

---

 there may be scenarios where recovery doesn't complete (due to failures encountered etc). this leads to two questions which need to be dealt with in the context of #14 and would need to be resolved before this PR in it's current form can be merged (since it's merger will close #14). if needed, the commit could be reworded if we don't want to wait for the questions below before merging this PR (resolving questions will take time). the questions are:
- [ ] what are the scenarios (failure or otherwise) that would lead to onRecoveryCompleted does not fire
- [ ] how should we behave in such scenarios? should we still run the job from the date in question obeying the reset flag?
- [ ] updates to the code implementing any tweaks identified above

---

In my opinion, the strategy of dealing with actor failures has a wider scope than the current bugfix. Therefore, I suggest to open another issue to continue this discussion.

### PR DESCRIPTION
**Pull request by dmitri-carpov**

### CODE REVIEW

**Comment by dmitri-carpov** [comment]
@WadeWaldron @jonas @sheenaluu @suhailshergill please review

File: src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+import scala.concurrent.ExecutionContext.Implicits.global
+
+object ProcessSupervisor {
+  def props(process: StagedProcess, date: Option[Date])(implicit messagingSystem: MessagingSystem) = Props(new ProcessSupervisor(process, date))
+
+  case object Done
+  case object Failed
+}
+
+class ProcessSupervisor(val process: StagedProcess, val startDate: Option[Date])(implicit val messagingSystem: MessagingSystem) extends Actor {
```
Comment (WadeWaldron) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: I would suggest that rather than defining all the shutdown logic here, and then passing in all the necessary dependencies to perform the shutdown, it might be easier just to pass in a "shutdown" function.  Then externally, in the place where we create those dependencies we can also define that shutdown function.

The job of this class is then just to call that shutdown function at the appropriate time.

File: src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+
+  context.watch(processManager)
+
+  override def supervisorStrategy: SupervisorStrategy = OneForOneStrategy() {
+    case _ => Stop
+  }
+
+  override def receive: Receive = {
+    case ProcessSupervisor.Done => stopSystem(0)
+    case ProcessSupervisor.Failed => stopSystem(1)
```
Comment (yawaramin) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: You could combine these two cases into `case ProcessSupervisor.Failed | Terminated(processManager) => stopSystem(1)`

Note that I didn't use backticks for `processManager` to avoid confusing the Markdown parser. Which actually leads me to the question: why use backticks here? The name is a valid Scala identifier name; backticks don't seem to be necessary.

Comment (WadeWaldron) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: Backticks would be necessary because without them it would just create a variable named "processManager" and fill it with the value, rather than actually trying to match on the value of processManager.  We would end up with shadowing. So this is correct.

File: src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+    case message => processManager.forward(message)
+  }
+
+  /**
+   * System shutdown logic.
+   */
+  private def stopSystem(code: Int): Unit = {
+    Try(messagingSystem.stop())
+
+    context.system.terminate().onComplete {
```
Comment (yawaramin) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: Can we send a poison pill to the top-level actor system?

**Comment by yawaramin** [comment]
+1 with a couple of questions :-)

File: src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala (hunk 3 above)
Comment (WadeWaldron) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: I don't think sending a poison pill is better in any way than what we are doing here.

File: src/main/scala/com.mediative.eigenflow/EigenflowBootstrap.scala [hunk 4]
```diff
@@ -47,17 +44,5 @@ trait EigenflowBootstrap {
   implicit val system = ActorSystem("DataFlow", ConfigurationLoader.config)
 
   // create main actor and tell to proceed.
-  system.actorOf(Props(new ProcessManager(process, startDate, stopSystem _))) ! Continue
-
-  /**
-   * System shutdown logic.
-   */
-  private def stopSystem(code: Int): Unit = {
```
Comment (WadeWaldron) [inline src/main/scala/com.mediative.eigenflow/EigenflowBootstrap.scala:55]: See the comment I have below.  I would keep this stopSystem here, and instead pass the function into the supervisor.  I prefer that pattern because it means the thing that creates the messaging system and actor system will also have the responsibility of shutting it down.

File: src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala (hunk 1 above)
Comment (dmitri-carpov) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: @WadeWaldron yes moving shutdown functionality to `EigenflowBootstrap` makes sense.

File: src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala (hunk 3 above)
Comment (dmitri-carpov) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: @yawaramin poison pill can terminate an actor but not the actor system.

File: src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala (hunk 2 above)
Comment (yawaramin) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: @WadeWaldron interesting! I always assumed the idiom for this behaviour is `case Terminated(pm) if pm == processManager => ...`; at least that's what I've seen so far. Didn't know about the backticks substituting in literal values of the given names!

File: src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala (hunk 3 above)
Comment (yawaramin) [inline src/main/scala/com.mediative.eigenflow/process/ProcessSupervisor.scala]: @dmitri-carpov @WadeWaldron sorry, that was a half-assed comment on my part. I meant actually the 'reaper' pattern which includes using poison pills to safely shut down individual actors: http://letitcrash.com/post/30165507578/shutdown-patterns-in-akka-2 (see section titled 'The Reaper').
